version: "3.8"
services:
    server:
      image: server
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: ${SERVER_HOST}
      env_file: .env
      ports:
        - ${SERVER_PORT}:${SERVER_PORT}
      depends_on: 
        - redis-cache
    redis-cache:
      container_name: redis
      image: redis:alpine3.16
      ports:
        - 6379:6379